{% set name = "dejaq" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dejaq-{{ version }}.tar.gz
  sha256: 4858dead694264a80b2aa6ffebd18826e1b8dba110d20c90133c504731f6e925

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools >=42
    - wheel
    - pip
  run:
    - python
    - numpy
    - tqdm
    - posix_ipc  # [unix]
    - pywin32    # [win]
    - cloudpickle
    - psutil

test:
  imports:
    - dejaq
  commands:
    - pip check
  requires:
    - python
    - pip

about:
  home: https://github.com/danionella/dejaq
  summary: Déjà Queue – A fast multiprocessing queue for Python
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - bjudkewitz
